id: I113C201E
default_language: bo
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-09 14:46:46.144737
last_modified: 2023-02-09 14:46:46.144893
source_metadata:
  title: 'PP: Prajñāpāramitāhṛdaya'
  language: bo
bases:
  021B:
    base_file: 021B.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
